# Generated by Django 5.0.3 on 2024-07-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_desc_task_task_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task_Desc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Task_Title',
            new_name='title',
        ),
    ]
